export type JobPosting = {
  title: string;
  company_name: string;
  gmail_message_id: string;
  job_uuid: string;
  source: string;
  application_deadline?: string | null;
  benefits?: string;
  company_logo_url?: string;
  company_url?: string;
  created_at?: string;
  date_posted?: string | null;
  employment_type?: string;
  experience_level?: string;
  fetched_at?: string;
  gmail_thread_id?: string;
  industries?: string;
  job_description_snippet?: string;
  job_type?: string;
  job_url?: string;
  location?: string;
  match_score?: number;
  salary?: string;
  skills?: string[];
  status?: string;
  summary?: string;
  updated_at?: string;
};
